import React, { useState } from 'react';
import useAuthStore from '../store/authStore';
import { 
  LayoutDashboard, 
  FileText, 
  PlusSquare, 
  FileEdit, 
  BarChart3, 
  Bookmark, 
  UserCircle, 
  Settings as SettingsIcon, 
  Menu, 
  X, 
  Eye, 
  ThumbsUp, 
  Sparkles, 
  TrendingUp,
  LogOut
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';

const Dashboard = () => {
  const { user, logout } = useAuthStore();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('overview');
  const [sidebarOpen, setSidebarOpen] = useState(false);

  // States for embedded blog creation
  const [newTitle, setNewTitle] = useState('');
  const [newTag, setNewTag] = useState('Technology');
  const [newSummary, setNewSummary] = useState('');
  const [newContent, setNewContent] = useState('');
  const [loading, setLoading] = useState(false);

  const handleLogout = () => {
    logout();
    toast.success('Logged out successfully');
    navigate('/login');
  };

  const handlePublish = (e) => {
    e.preventDefault();
    if (!newTitle || !newSummary || !newContent) {
      toast.error('Please fill in all fields before publishing');
      return;
    }
    toast.success('Article published successfully (Simulated)!');
    setNewTitle('');
    setNewSummary('');
    setNewContent('');
    setActiveTab('my-blogs');
  };

  const handleAiAutoWrite = () => {
    if (!newTitle) {
      toast.error('Enter a title to generate content');
      return;
    }
    toast.loading('Gemini is generating content...');
    setTimeout(() => {
      toast.dismiss();
      setNewContent(`<h2>Insights on ${newTitle}</h2><p>This is a structured article generated by Gemini AI covering <strong>${newTitle}</strong>. It outlines key methodologies, future outlooks, and implementation strategies for engineers.</p>`);
      setNewSummary(`An exploration of ${newTitle} and its long-term industry impact.`);
      toast.success('AI generation finished!');
    }, 1500);
  };

  const menuItems = [
    { id: 'overview', name: 'Dashboard', icon: LayoutDashboard },
    { id: 'my-blogs', name: 'My Blogs', icon: FileText },
    { id: 'create-blog', name: 'Create Blog', icon: PlusSquare },
    { id: 'drafts', name: 'Drafts', icon: FileEdit },
    { id: 'analytics', name: 'Analytics', icon: BarChart3 },
    { id: 'bookmarks', name: 'Bookmarks', icon: Bookmark },
    { id: 'profile', name: 'Profile', icon: UserCircle },
    { id: 'settings', name: 'Settings', icon: SettingsIcon },
  ];

  return (
    <div className="flex min-h-screen bg-slate-950 text-slate-100 font-sans antialiased">
      {/* Mobile Sidebar Toggle */}
      <button 
        onClick={() => setSidebarOpen(!sidebarOpen)}
        className="fixed top-4 left-4 z-50 p-2 bg-slate-900 border border-slate-800 rounded-lg lg:hidden focus:outline-none"
      >
        {sidebarOpen ? <X size={20} /> : <Menu size={20} />}
      </button>

      {/* Sidebar Navigation */}
      <aside className={`
        fixed inset-y-0 left-0 z-40 w-64 bg-slate-900/90 border-r border-slate-800 backdrop-blur-md transform transition-transform duration-300 ease-in-out lg:translate-x-0 lg:static lg:block
        ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}
      `}>
        <div className="flex flex-col h-full">
          {/* Logo Area */}
          <div className="p-6 border-b border-slate-800">
            <span className="text-2xl font-extrabold bg-gradient-to-r from-violet-500 to-cyan-400 bg-clip-text text-transparent tracking-tight">
              AI BlogForge
            </span>
          </div>

          {/* Menu Items */}
          <nav className="flex-1 px-4 py-6 space-y-1 overflow-y-auto">
            {menuItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.id}
                  onClick={() => {
                    setActiveTab(item.id);
                    setSidebarOpen(false);
                  }}
                  className={`
                    flex items-center w-full gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-all duration-200
                    ${activeTab === item.id 
                      ? 'bg-violet-600 text-white shadow-lg shadow-violet-500/20' 
                      : 'text-slate-400 hover:bg-slate-800/60 hover:text-slate-200'}
                  `}
                >
                  <Icon size={18} />
                  {item.name}
                </button>
              );
            })}
          </nav>

          {/* User Profile Summary */}
          <div className="p-4 border-t border-slate-800 bg-slate-950/40">
            <div className="flex items-center gap-3 mb-3">
              <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-tr from-violet-500 to-cyan-500 text-white font-bold">
                {user?.name?.[0]?.toUpperCase() || 'U'}
              </div>
              <div className="overflow-hidden">
                <p className="text-sm font-semibold truncate text-slate-200">{user?.name || 'Author'}</p>
                <p className="text-xs text-slate-500 truncate">{user?.email || 'author@blogforge.com'}</p>
              </div>
            </div>
            <button 
              onClick={handleLogout}
              className="flex items-center justify-center w-full gap-2 px-3 py-2 text-xs font-semibold text-rose-400 border border-rose-950/30 bg-rose-950/10 rounded-lg hover:bg-rose-950/30 transition"
            >
              <LogOut size={14} />
              Logout Session
            </button>
          </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 min-w-0 overflow-y-auto bg-slate-950 p-6 lg:p-10">
        <div className="max-w-6xl mx-auto mt-8 lg:mt-0">
          
          {/* Header Row */}
          <div className="flex flex-col gap-2 md:flex-row md:justify-between md:items-center mb-8 pb-6 border-b border-slate-800/80">
            <div>
              <h1 className="text-3xl font-extrabold tracking-tight text-white capitalize">
                {activeTab.replace('-', ' ')}
              </h1>
              <p className="text-sm text-slate-400">
                Welcome back to your workspace, {user?.name || 'Author'}.
              </p>
            </div>
            {activeTab !== 'create-blog' && (
              <button 
                onClick={() => setActiveTab('create-blog')}
                className="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-violet-600 rounded-lg hover:bg-violet-500 shadow-md hover:shadow-violet-600/10 transition"
              >
                <PlusSquare size={16} />
                Create New Post
              </button>
            )}
          </div>

          {/* Dynamically Rendered Tab Views */}
          
          {/* 1. Overview Tab */}
          {activeTab === 'overview' && (
            <div className="space-y-8">
              {/* Stats Grid */}
              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
                {[
                  { title: 'Total Blogs', count: '12', icon: FileText, color: 'text-violet-500' },
                  { title: 'Monthly Views', count: '4,821', icon: Eye, trend: '+12.4%', color: 'text-cyan-500' },
                  { title: 'Submissions/Likes', count: '942', icon: ThumbsUp, color: 'text-emerald-500' },
                  { title: 'AI Assistant Queries', count: '38', icon: Sparkles, color: 'text-amber-500' }
                ].map((stat, i) => {
                  const StatIcon = stat.icon;
                  return (
                    <div key={i} className="p-6 bg-slate-900 border border-slate-800 rounded-xl hover:border-slate-700 transition">
                      <div className="flex justify-between items-start mb-4">
                        <span className="text-sm font-medium text-slate-400">{stat.title}</span>
                        <StatIcon className={stat.color} size={20} />
                      </div>
                      <div className="flex items-baseline gap-2">
                        <span className="text-3xl font-bold tracking-tight text-white">{stat.count}</span>
                        {stat.trend && (
                          <span className="text-xs font-semibold text-emerald-400 flex items-center gap-0.5">
                            <TrendingUp size={12} />
                            {stat.trend}
                          </span>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Grid sections for activities & tags */}
              <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
                {/* Recent Activities */}
                <div className="lg:col-span-2 p-6 bg-slate-900 border border-slate-800 rounded-xl">
                  <h3 className="text-lg font-bold mb-4">Recent Activities</h3>
                  <div className="space-y-4">
                    {[
                      { action: 'Published article', name: 'The Future of AI in Web Development', time: '2 hours ago', icon: FileText, tag: 'Technology' },
                      { action: 'Edited draft', name: 'Premium Glassmorphic Designs', time: '1 day ago', icon: FileEdit, tag: 'Design' },
                      { action: 'Bookmarked post', name: 'Unlocking Gemini API in Express', time: '3 days ago', icon: Bookmark, tag: 'AI Integration' }
                    ].map((act, i) => {
                      const ActIcon = act.icon;
                      return (
                        <div key={i} className="flex justify-between items-center p-3 rounded-lg bg-slate-950 border border-slate-850 hover:border-slate-800 transition">
                          <div className="flex items-center gap-3">
                            <div className="p-2 bg-slate-900 text-slate-300 rounded-lg">
                              <ActIcon size={16} />
                            </div>
                            <div>
                              <p className="text-sm font-semibold text-slate-200">
                                {act.action} <span className="text-violet-400">"{act.name}"</span>
                              </p>
                              <span className="text-xs text-slate-500">{act.time}</span>
                            </div>
                          </div>
                          <span className="text-xs px-2 py-1 bg-slate-900 border border-slate-800 text-slate-400 rounded-full">{act.tag}</span>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Popular Tags */}
                <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl">
                  <h3 className="text-lg font-bold mb-4">Tag Performance</h3>
                  <div className="space-y-4">
                    {[
                      { name: 'Technology', percentage: '75%', color: 'bg-violet-600' },
                      { name: 'AI Integration', percentage: '60%', color: 'bg-cyan-500' },
                      { name: 'Design', percentage: '45%', color: 'bg-emerald-500' },
                      { name: 'Development', percentage: '30%', color: 'bg-amber-500' }
                    ].map((tag, i) => (
                      <div key={i} className="space-y-1.5">
                        <div className="flex justify-between text-xs font-semibold">
                          <span>{tag.name}</span>
                          <span>{tag.percentage}</span>
                        </div>
                        <div className="h-2 w-full bg-slate-950 rounded-full overflow-hidden">
                          <div className={`h-full ${tag.color} rounded-full`} style={{ width: tag.percentage }}></div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* 2. My Blogs Tab */}
          {activeTab === 'my-blogs' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {[
                { title: 'The Future of AI in Web Development', desc: 'Exploring next-gen compiler engines, code suggestion bots, and dynamic user interfaces.', views: 342, likes: 89, date: 'July 12, 2026', tag: 'Technology' },
                { title: 'Unlocking Gemini AI Capabilities in Express', desc: 'How to build controllers to fetch schema structures directly using Google GenAI SDK.', views: 245, likes: 62, date: 'July 10, 2026', tag: 'AI Integration' }
              ].map((blog, i) => (
                <div key={i} className="flex flex-col bg-slate-900 border border-slate-800 rounded-xl overflow-hidden hover:border-slate-700 transition">
                  <div className="p-6 flex-grow">
                    <span className="inline-block text-xs font-bold text-violet-400 bg-violet-950/40 px-2.5 py-1 rounded-full uppercase tracking-wider mb-3">
                      {blog.tag}
                    </span>
                    <h3 className="text-xl font-bold mb-2 text-white">{blog.title}</h3>
                    <p className="text-sm text-slate-400">{blog.desc}</p>
                  </div>
                  <div className="px-6 py-4 bg-slate-950 border-t border-slate-800/60 flex justify-between items-center text-xs text-slate-500">
                    <span>Published: {blog.date}</span>
                    <div className="flex gap-4">
                      <span className="flex items-center gap-1"><Eye size={14} /> {blog.views}</span>
                      <span className="flex items-center gap-1"><ThumbsUp size={14} /> {blog.likes}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* 3. Create Blog Tab (Embedded Form) */}
          {activeTab === 'create-blog' && (
            <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl max-w-3xl mx-auto">
              <form onSubmit={handlePublish} className="space-y-6">
                <div>
                  <label className="block text-sm font-semibold mb-2 text-slate-350 text-left">Post Title</label>
                  <input 
                    type="text" 
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-violet-600 focus:ring-1 focus:ring-violet-600 transition" 
                    placeholder="Enter blog post title"
                    value={newTitle} 
                    onChange={(e) => setNewTitle(e.target.value)} 
                    required 
                  />
                </div>

                <div className="flex flex-col gap-4 sm:flex-row sm:items-end">
                  <div className="flex-1">
                    <label className="block text-sm font-semibold mb-2 text-slate-350 text-left">Category / Tag</label>
                    <select 
                      className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-violet-600 transition"
                      value={newTag} 
                      onChange={(e) => setNewTag(e.target.value)}
                    >
                      <option>Technology</option>
                      <option>Design</option>
                      <option>AI Integration</option>
                      <option>Development</option>
                    </select>
                  </div>
                  <button
                    type="button"
                    onClick={handleAiAutoWrite}
                    className="h-[46px] inline-flex items-center justify-center gap-2 px-4 rounded-lg bg-cyan-950/30 border border-cyan-800/80 text-cyan-400 font-semibold hover:bg-cyan-950/60 transition"
                  >
                    <Sparkles size={16} />
                    Auto-Generate content with Gemini
                  </button>
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-2 text-slate-350 text-left">Short Summary</label>
                  <input 
                    type="text" 
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-violet-600 focus:ring-1 focus:ring-violet-600 transition" 
                    placeholder="Brief overview summarizing the article"
                    value={newSummary} 
                    onChange={(e) => setNewSummary(e.target.value)} 
                    required 
                  />
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-2 text-slate-350 text-left">Body Content</label>
                  <div className="bg-slate-950 rounded-lg overflow-hidden border border-slate-800">
                    <ReactQuill theme="snow" value={newContent} onChange={setNewContent} />
                  </div>
                </div>

                <div className="flex justify-end gap-3 pt-4 border-t border-slate-800">
                  <button 
                    type="button" 
                    onClick={() => setActiveTab('overview')}
                    className="px-4 py-2 border border-slate-850 hover:bg-slate-800 rounded-lg text-sm font-semibold"
                  >
                    Cancel
                  </button>
                  <button 
                    type="submit" 
                    className="px-5 py-2 bg-violet-600 hover:bg-violet-500 rounded-lg text-sm font-semibold text-white shadow-md hover:shadow-violet-600/10 transition"
                  >
                    Publish Blog
                  </button>
                </div>
              </form>
            </div>
          )}

          {/* 4. Drafts Tab */}
          {activeTab === 'drafts' && (
            <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl">
              <p className="text-slate-400 text-sm mb-4">You have 1 draft saved.</p>
              <div className="p-4 rounded-lg bg-slate-950 border border-slate-850 flex justify-between items-center">
                <div>
                  <h4 className="font-bold text-white mb-1">Premium Glassmorphic Designs</h4>
                  <span className="text-xs text-slate-500">Last saved: 1 day ago</span>
                </div>
                <button 
                  onClick={() => {
                    setNewTitle('Premium Glassmorphic Designs');
                    setNewTag('Design');
                    setNewSummary('A step-by-step guide to building glassmorphism interfaces.');
                    setNewContent('<h2>Crafting Glassmorphism</h2><p>Here is how you start with CSS backgrounds and blur backdrops.</p>');
                    setActiveTab('create-blog');
                  }}
                  className="px-3.5 py-1.5 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-semibold rounded-lg transition"
                >
                  Resume Draft
                </button>
              </div>
            </div>
          )}

          {/* 5. Analytics Tab */}
          {activeTab === 'analytics' && (
            <div className="space-y-6">
              <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl">
                <h3 className="text-lg font-bold mb-6">Views Over Time</h3>
                {/* Simulated Chart */}
                <div className="flex items-end justify-between gap-2 h-48 px-4 pt-4 border-b border-slate-800 border-l">
                  {[45, 60, 30, 80, 50, 95, 70].map((val, i) => (
                    <div key={i} className="flex-1 flex flex-col items-center gap-2 group">
                      <div className="w-full bg-violet-600 group-hover:bg-violet-500 rounded-t transition-all duration-300" style={{ height: `${val}%` }}></div>
                      <span className="text-[10px] text-slate-500 font-semibold">Day {i + 1}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* 6. Bookmarks Tab */}
          {activeTab === 'bookmarks' && (
            <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl">
              <p className="text-slate-400 text-sm">No saved bookmarks yet. Go explore the Home page to save articles!</p>
            </div>
          )}

          {/* 7. Profile Tab */}
          {activeTab === 'profile' && (
            <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl max-w-2xl mx-auto">
              <div className="flex flex-col sm:flex-row items-center gap-6 mb-8">
                <div className="w-20 h-20 rounded-full bg-gradient-to-tr from-violet-500 to-cyan-500 flex items-center justify-center text-2xl font-bold text-white shadow-xl shadow-violet-500/10">
                  {user?.name?.[0]?.toUpperCase() || 'U'}
                </div>
                <div className="text-center sm:text-left">
                  <h3 className="text-xl font-bold text-white">{user?.name || 'Author'}</h3>
                  <p className="text-sm text-slate-400">{user?.email || 'author@blogforge.com'}</p>
                  <p className="text-xs text-slate-500 mt-1">Access Tier: Professional Writer</p>
                </div>
              </div>

              <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); toast.success('Profile updated (Simulated)'); }}>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold mb-2 text-slate-400 text-left">Full Name</label>
                    <input type="text" className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-sm text-white" defaultValue={user?.name} />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold mb-2 text-slate-400 text-left">Email Address</label>
                    <input type="email" className="w-full bg-slate-950 border border-slate-850 rounded-lg px-4 py-2.5 text-sm text-slate-500" defaultValue={user?.email} disabled />
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-semibold mb-2 text-slate-400 text-left">Short Bio</label>
                  <textarea className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-sm text-white h-24" placeholder="Tell us about yourself..."></textarea>
                </div>
                <button type="submit" className="px-4 py-2 bg-violet-600 hover:bg-violet-500 text-sm font-semibold rounded-lg text-white transition">
                  Save Profile
                </button>
              </form>
            </div>
          )}

          {/* 8. Settings Tab */}
          {activeTab === 'settings' && (
            <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl max-w-2xl mx-auto space-y-6">
              <div>
                <h3 className="font-bold text-white mb-2">Workspace Settings</h3>
                <p className="text-xs text-slate-500 mb-4">Configure preferences for drafts auto-save and newsletter mailings.</p>
                <div className="space-y-3">
                  {[
                    { label: 'Auto-save drafts', desc: 'Saves your changes locally every 30 seconds' },
                    { label: 'Email notifications', desc: 'Receive emails when your articles get new views or comments' }
                  ].map((sett, i) => (
                    <label key={i} className="flex justify-between items-center p-3 rounded-lg bg-slate-950 border border-slate-850 cursor-pointer">
                      <div>
                        <p className="text-sm font-semibold text-slate-200">{sett.label}</p>
                        <p className="text-xs text-slate-500">{sett.desc}</p>
                      </div>
                      <input type="checkbox" defaultChecked className="w-4 h-4 accent-violet-600" />
                    </label>
                  ))}
                </div>
              </div>
            </div>
          )}

        </div>
      </main>
    </div>
  );
};

export default Dashboard;
