import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import toast from 'react-hot-toast';

const CreatePost = () => {
  const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [tag, setTag] = useState('Technology');
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(false);
  const [aiGenerating, setAiGenerating] = useState(false);

  useEffect(() => {
    document.title = 'Create Post | AI BlogForge';
  }, []);

  const handleAiGenerate = async () => {
    if (!title) {
      toast.error('Please enter a Title first so the AI knows what to write!');
      return;
    }
    setAiGenerating(true);
    const toastId = toast.loading('Gemini is forging your post content...');
    try {
      const response = await api.post('/posts/generate', { prompt: title });
      setContent(response.data?.generatedContent || '');
      setDescription(response.data?.summary || `An AI-generated article exploring ${title}.`);
      toast.success('AI Content generated successfully!', { id: toastId });
    } catch (error) {
      console.error(error);
      toast.error('Failed to generate AI content, using fallback template.', { id: toastId });
      // Fallback AI generated content for dev demo
      setContent(`<h2>Exploring ${title}</h2><p>This is a high-quality article about <strong>${title}</strong> generated by Gemini AI. It explores various aspects of the topic and provides structured insights.</p><p>We can look at three main points:</p><ul><li>Dynamic integrations and developer velocity.</li><li>Rich user experience utilizing glassmorphism and modern UI layouts.</li><li>Modular backend architectures using Node, Express, and MongoDB.</li></ul>`);
      setDescription(`An AI-generated article exploring ${title}.`);
    } finally {
      setAiGenerating(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!title || !description || !content) {
      toast.error('Please fill in all fields (Title, Summary, Content)');
      return;
    }
    setLoading(true);
    try {
      await api.post('/posts', { title, description, category: tag, content });
      toast.success('Blog post published successfully!');
      navigate('/');
    } catch (error) {
      console.error('Submit error:', error);
      toast.error('Failed to publish article.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="main-content">
      <div className="create-blog-container">
        <h2 style={{ fontSize: '32px', marginBottom: '24px', textAlign: 'left' }}>Create New Post</h2>
      
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label className="form-label">Article Title</label>
          <input 
            type="text" 
            className="form-input" 
            placeholder="e.g. The Future of Quantum Computing"
            value={title} 
            onChange={(e) => setTitle(e.target.value)} 
            required
          />
        </div>

        <div className="form-group" style={{ display: 'flex', gap: '20px', alignItems: 'flex-end' }}>
          <div style={{ flexGrow: 1 }}>
            <label className="form-label">Category / Tag</label>
            <select 
              className="form-input" 
              value={tag} 
              onChange={(e) => setTag(e.target.value)}
            >
              <option value="Technology">Technology</option>
              <option value="Design">Design</option>
              <option value="AI Integration">AI Integration</option>
              <option value="Development">Development</option>
              <option value="Business">Business</option>
            </select>
          </div>
          
          <button 
            type="button" 
            className="btn btn-secondary" 
            onClick={handleAiGenerate}
            disabled={aiGenerating}
            style={{ 
              height: '46px', 
              background: 'linear-gradient(135deg, rgba(6, 182, 212, 0.2), rgba(139, 92, 246, 0.2))',
              border: '1px solid var(--primary-hover)'
            }}
          >
            {aiGenerating ? 'Forging Content...' : '✨ Generate Content with AI'}
          </button>
        </div>

        <div className="form-group">
          <label className="form-label">Short Summary</label>
          <input 
            type="text" 
            className="form-input" 
            placeholder="Brief overview summarizing the article..."
            value={description} 
            onChange={(e) => setDescription(e.target.value)}
            required
          />
        </div>

        <div className="form-group">
          <label className="form-label">Body Content</label>
          <div className="editor-wrapper">
            <textarea
              value={content}
              onChange={(event) => setContent(event.target.value)}
              rows={14}
              placeholder="Write your article here..."
              className="block w-full resize-y bg-transparent px-4 py-3 text-[15px] leading-7 text-slate-100 placeholder:text-slate-600 focus:outline-none"
            />
          </div>
        </div>

        <div style={{ display: 'flex', gap: '15px', justifyContent: 'flex-end', marginTop: '30px' }}>
          <button type="button" className="btn btn-secondary" onClick={() => navigate('/')}>
            Cancel
          </button>
          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? 'Publishing...' : 'Publish Article'}
          </button>
        </div>
      </form>
    </div>
  </div>
  );
};

export default CreatePost;
