const { GoogleGenAI } = require('@google/genai');

const getPromptForAction = (action, prompt, content) => {
  switch (action) {
    case 'generate':
      return `Write a high-quality, engaging blog post about: "${prompt}". Return it in beautiful HTML format suitable for rendering inside a rich-text editor (using tags like <h2>, <p>, <ul>, <li>, and <strong>). Do not include markdown fences, HTML wrapper tags like <html>, <head>, <body>, or code blocks unless requested. Keep it around 400 words.`;
    case 'continue':
      return `Given the following partial content of a blog post, continue writing the next section naturally. Keep the tone and style consistent. Return ONLY the new continued content in HTML format without markdown fences or HTML wrappers:\n\n${content}`;
    case 'rewrite':
      return `Rewrite the following blog content to make it more professional, engaging, and polished. Keep it in HTML format without markdown fences or HTML wrappers:\n\n${content}`;
    case 'grammar':
      return `Fix any grammar, spelling, and punctuation errors in the following blog content while preserving its original meaning and HTML tags. Return the polished version in HTML format without markdown fences or HTML wrappers:\n\n${content}`;
    case 'summarize':
      return `Create a concise, professional summary of the following blog content. Return it in HTML format (using <p> and bullet points if needed) without markdown fences or HTML wrappers:\n\n${content}`;
    case 'meta':
      return `Generate a high-quality SEO meta description (under 160 characters) for a blog post with the following content. Return ONLY the plain text meta description without quotes:\n\n${content}`;
    case 'titles':
      return `Generate 5 catchy, SEO-friendly headlines/titles for a blog post about "${prompt || ''}" (or with content "${content || ''}"). Return them as a clean HTML bulleted list (<ul> and <li> tags) without markdown fences or HTML wrappers.`;
    case 'tags':
      return `Generate 8 relevant, trending hashtags/tags for a blog post with the following content. Return them as a comma-separated list of hashtags (e.g. #WebDev, #AI, #Tech) in plain text:\n\n${content}`;
    default:
      return prompt || '';
  }
};

const getMockupText = (action, prompt, content) => {
  switch (action) {
    case 'generate':
      return `<h2>Overview of ${prompt || 'New Topic'}</h2><p>This is a structured article generated by Gemini AI regarding <strong>${prompt || 'New Topic'}</strong>. It outlines key methodologies, future outlooks, and implementation strategies for developers and designers alike.</p><p>Here are three core areas of impact:</p><ul><li><strong>Speed & Automation:</strong> Accelerating deployment cycles with modern full-stack workflows.</li><li><strong>Premium Presentation:</strong> Utilizing rich dark modes, glassmorphism, and smooth micro-interactions.</li><li><strong>Secure APIs:</strong> Enforcing stateful protections with HTTP-only cookies and modular controllers.</li></ul><p>By leveraging intelligent tools, authors can focus on structuring great ideas while the AI manages boilerplate prose.</p>`;
    case 'continue':
      return `<p>Building on top of this, we also need to consider security and state management. When endpoints require authentication, enforcing cookie validation prevents CSRF attacks. Combining this with Zustand stores on the frontend creates a robust, synchronized experience for users across any browser tab.</p>`;
    case 'rewrite':
      return `<p>Here is a polished version of your content: Designing modern interfaces requires both rich visual elements and high-performance routing. By combining Vite for compile-time speed and Tailwind CSS for glassmorphic style controls, we achieve an optimal balance between user satisfaction and engineering efficiency.</p>`;
    case 'grammar':
      return `<p>The spelling and grammatical issues have been resolved. The layout now aligns perfectly, and our database connection runs as expected. We are ready to scale production deployments safely.</p>`;
    case 'summarize':
      return `<p><strong>Executive Summary:</strong></p><ul><li>A modular MERN setup using Vite, Express, and Mongoose.</li><li>Secure authentication handled via HTTP-only JWT cookies.</li><li>Dynamic dashboard tools with live word counters and Gemini AI auto-writers.</li></ul>`;
    case 'meta':
      return `Learn how to build full-stack MERN apps with Vite, Tailwind CSS v4, and integrated Google Gemini AI streaming workflows in this complete guide.`;
    case 'titles':
      return `<ul><li>5 Pro Tips for Building MERN Stack Applications</li><li>Unlocking Gemini AI Streaming inside Node.js Express</li><li>Designing Stunning Dark Mode Dashboards with Tailwind v4</li><li>MERN CRUD Operations: The Definitive Guide</li><li>Securing REST APIs with HTTP-Only JWT Cookies</li></ul>`;
    case 'tags':
      return `#MERNStack, #ReactJS, #Vite, #TailwindCSS, #GeminiAI, #FullStack, #WebDev, #ExpressJS`;
    default:
      return `Generated mockup response for action: ${action}`;
  }
};

const runAiTask = async (action, prompt, content) => {
  const promptText = getPromptForAction(action, prompt, content);
  
  if (process.env.GEMINI_API_KEY) {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: promptText,
    });
    return response.text || '';
  } else {
    return getMockupText(action, prompt, content);
  }
};

const runAiTaskStream = async (action, prompt, content, onChunk, onDone) => {
  const promptText = getPromptForAction(action, prompt, content);
  
  if (process.env.GEMINI_API_KEY) {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    const responseStream = await ai.models.generateContentStream({
      model: 'gemini-2.5-flash',
      contents: promptText,
    });
    for await (const chunk of responseStream) {
      if (chunk.text) {
        onChunk(chunk.text);
      }
    }
    if (onDone) onDone();
  } else {
    // Offline simulation
    const mockupText = getMockupText(action, prompt, content);
    const words = mockupText.split(' ');
    let i = 0;
    
    return new Promise((resolve) => {
      const interval = setInterval(() => {
        if (i < words.length) {
          const chunk = words.slice(i, i + 4).join(' ') + ' ';
          onChunk(chunk);
          i += 4;
        } else {
          clearInterval(interval);
          if (onDone) onDone();
          resolve();
        }
      }, 100);
    });
  }
};

module.exports = {
  getPromptForAction,
  getMockupText,
  runAiTask,
  runAiTaskStream,
};
